config/routes.rb
Ca::Application.routes.draw do

  root "static_pages#home"
  get "/chat", to: "static_pages#chat"
  get "/about", to: "static_pages#about"
  get "/terms", to: "static_pages#terms"
  get "/privacy", to: "static_pages#privacy"

  # Doesn't create any routes, simply enables Devise helpers for User objects
  devise_for :user, skip: [:sessions, :registrations, :passwords, :confirmations]

  devise_scope :user do
    post '/login', to: 'sessions#create', as: :user_session
    delete '/logout', to: 'sessions#destroy', as: :destroy_user_session

    post '/signup', to: 'registrations#create', as: :user_registration

    get '/forgot_password', to: 'passwords#new', as: :new_user_password
    post '/forgot_password', to: 'passwords#create', as: :user_password
    get '/reset_password', to: 'passwords#edit', as: :edit_user_password
    patch '/reset_password', to: 'passwords#update'
    put '/reset_password', to: 'passwords#update'

    post '/confirm_account', to: 'confirmations#create', as: :user_confirmation
    get '/confirm_account', to: 'confirmations#show'
  end

end

app/models/failed_signup.rb
class FailedSignup < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :users

  validates :name, presence: true, uniqueness: true

  def proper_name
    case name
    when "upenn"
      "Penn"
    else
      name.titleize
    end
  end

  # use the name as the slug
  # https://gist.github.com/cdmwebs/1209732
  def to_param
    name.parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :confirmable

  belongs_to :school

  before_validation :set_school_from_email

  validate :current_student
  validates :email, :school, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true, if: :password_required?

  EMAIL_REGEX = /\A[\w+\-.]+@((?<subdomains>.+)\.)*(?<school>.+)\.edu\z/i
  ALUMNI_SUBDOMAINS = %w(alumni cca post aya)

  def set_school_from_email
    match = EMAIL_REGEX.match(email)
    if match
      school = School.find_by(name: match[:school])
      if school
        self.school = school
      else
        errors.add(:school, "must be in the Ivy League")
      end
    else
      errors.add(:email, "must be an .edu email address")
    end
  end

  def current_student
    match = EMAIL_REGEX.match(email)
    if match
      subdomains = match[:subdomains]
      if subdomains
        ALUMNI_SUBDOMAINS.each do |alumni_subdomain|
          if subdomains.include? alumni_subdomain
            errors.add(:email, "can't be an alumni email address")
          end
        end
      end
    end
  end

  protected

  # Passwords are only required for new records because saved records
  # don't have a password field
  def password_required?
    !persisted?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

  def show
    super do |resource|
      unless resource.errors.empty?
        set_flash_message :alert, :already_confirmed
        redirect_to root_path
        return
      end
    end
  end

  protected

  def after_resending_confirmation_instructions_path_for(resource_name)
    root_path
  end

  def after_confirmation_path_for(resource_name, resource)
    if signed_in?(resource_name)
      signed_in_root_path(resource)
    else
      root_path
    end
  end

end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController

  protected
    def after_resetting_password_path_for(resource)
      after_sign_in_path_for(resource)
    end

    def after_sending_reset_password_instructions_path_for(resource_name)
      root_path
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def create
    build_resource(sign_up_params)

    resource_saved = resource.save
    if resource_saved
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up_but_unconfirmed if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      @validatable = devise_mapping.validatable?
      if @validatable
        @minimum_password_length = resource_class.password_length.min
      end

      if is_flashing_format?
        if resource.errors.keys.length == 1 && resource.errors.has_key?(:school)
          set_flash_message :alert, :not_an_ivy
          FailedSignup.create(email: resource.email)
        else
          messages = []
          resource.errors.keys.each do |attribute|
            messages.push(resource.errors.full_messages_for(attribute)) unless attribute == :school
          end
          flash[:alert] = messages.join('. ') + '.'
        end
      end
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def create
    super do |user|
      unless user.confirmed?
        set_flash_message(:notice, :signed_in_but_unconfirmed) if is_flashing_format?
      end
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: :chat

  def home
  end

  def about
  end

  def terms
  end

  def privacy
  end

  def chat
    if current_user.confirmed?
      session[:email] = current_user.email
      render layout: false
    elsif
      redirect_to root_url, alert: "Please confirm your account."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head prefix="og: http://ogp.me/ns#">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title><%= content_for?(:title) ? yield(:title) : "Campus Anonymous" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Campus Anonymous connects college students anonymously.' %>">
    <meta property="og:title" content="Campus Anonymous">
    <meta property="og:description" content="There are amazing people in the Ivy League you've never met.">
    <meta property="og:url" content="http://www.campusanonymous.com">
    <meta property="og:image" content="<%= image_url('fb-og-image.png') %>">
    <meta property="fb:app_id" content="<%= Rails.application.secrets.fb_app_id %>">
    <%= favicon_link_tag 'favicon.png' %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", media: "all" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <script>
      window.fbAsyncInit = function() {
       FB.init({
         appId      : '<%= Rails.application.secrets.fb_app_id %>',
         xfbml      : true,
         version    : 'v2.2'
       });
      };
      (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
    <script>
      window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
    </script>
    <%= render 'shared/navigation' %>
    <%= render 'shared/messages' %>
    <div class="container">
      <%= content_for?(:devise) ? yield(:devise) : yield %>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<% content_for :devise do %>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <%= yield %>
      </div>
    </div>
  </div>
<% end %>
<%= render template: "layouts/application" %>

app/views/layouts/email.html.erb
<html>
  <head>
    <style>
      body {font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;}
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer row">
  <div class="col-sm-12">
    <hr/>
    <div>
      <%= link_to "About", "/about" %>
      <%= link_to "Follow", "https://twitter.com/intent/follow?screen_name=campusanonymous" %>
      <%= link_to "Share", "#", id: "fb-share" %>
      <%= link_to "Tweet", "https://twitter.com/intent/tweet?hashtags=CampusAnonymous&text=Check out Campus Anonymous%2C a way for Ivy League students to chat anonymously!&url=http%3A%2F%2Fwww.campusanonymous.com" %>
      <%= link_to "Terms", "/terms" %>
      <%= link_to "Privacy", "/privacy" %>
      <%= link_to "Forgot Password?", new_user_password_path %>
    </div>
  </div>
</div>

app/views/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<div class="container">
  <div class="flash-wrapper">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Campus Anonymous', root_path, class: 'navbar-brand' %>
    </div>
    <% if user_signed_in? %>
      <div class="navbar-right">
        <span class="navbar-text"><%= current_user.email %></span>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-danger navbar-btn' %>
      </div>
    <% else %>
      <%= bootstrap_form_for(User.new, url: user_session_path, html: { class: 'navbar-form navbar-right'}) do |f| %>
        <%= f.email_field :email, hide_label: true, placeholder: "Email" %>
        <%= f.password_field :password, hide_label: true, placeholder: "Password" %>
        <%= f.submit "Sign In", class: "btn btn-success" %>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/static_pages/about.html.erb
<h2>About</h2>
<div class="row bio">
  <div class="col-sm-6">
    <%= image_tag "dk.jpg", class: "img-circle img-responsive" %>
    <h3>Dan Kang</h3>
    <p>
      It was a dark and stormy night. Finally having surrendered to a tormenting problem set at 3am, I feebly shuffled back to my dorm alone. In the corner of my eye, I caught a stray glimmer of light from a dorm room window, silhouetting a similarly lonely soul toiling away into the wee hours of the night. I thought, "o*."<br><br>
      <small>* Campus Anonymous needs to exist</small>
    </p>
  </div>
  <div class="col-sm-6">
    <%= image_tag "akshay.jpg", class: "img-circle img-responsive" %>
    <h3>Akshay Kumar</h3>
    <p>
      Long conversations are kind of my thing: It’s the best feeling in the world when you say something and the other person just gets it. Know what I mean? Either way, I hope you enjoy Campus Anonymous as much as we enjoyed building it.
    </p>
  </div>
</div>

app/views/static_pages/chat.html.erb
<!DOCTYPE html>
<html ng-app="pom">
  <head ng-controller="TitleCtrl">
    <title ng-bind="getTitle()">Campus Anonymous</title>
    <%= favicon_link_tag 'favicon.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag "chat", media: "all" %>
  </head>
  <body ng-controller="ChatCtrl">
    <div id="fb-root"></div>
    <div class="nav">
      <div class="nav-container">
        <a class="brand" href="/">Campus Anonymous</a>
        <a class="volume" ng-click="playSound = !playSound" ng-cloak>
          <i class="fa fa-volume-up" ng-show="playSound"></i>
          <i class="fa fa-volume-off" ng-show="!playSound"></i>
        </a>
        <a class="circle-down" ng-show="dropdown.shouldShowMinimized() && state == 'chatting'" ng-click="dropdown.show()" ng-cloak>
          <i class="fa fa-chevron-circle-down"></i>
        </a>
      </div>
    </div>
    <div class="chat-container">
      <div class="dropdown" ng-show="dropdown.shouldShowFull() && state == 'chatting'" ng-cloak>
        <div class="question">
          Do you want to find out who you've been chatting with?<br>
          <span class="promise">We'll never post to Facebook without your permission. Promise.</span>
        </div>
        <div class="options">
          <button type="button" class="yes-btn" ng-click="dropdown.accept()">Yes</button>
          <button type="button" class="hide-btn" ng-click="dropdown.hide()">Hide</button>
        </div>
      </div>
      <div class="chatroom" pom-scroll-glue>
        <ul ng-cloak>
          <li ng-repeat="message in messages" ng-class="message.type" ng-switch="message.type">
            <div ng-switch-when="chat">
              <span ng-class="{ {{partner.school}}: message.isPartner }" class="userName" title="{{message.time}}">{{message.name}}:</span>
              <span ng-bind-html="message.text | linky | linkyNewlines"></span>
            </div>
            <div ng-switch-when="system">
              <div ng-switch="message.template" ng-class="{important: message.important}">
                <div ng-switch-when="waiting">
                  Waiting for another Ivy League student to join...<br>
                  Feel free to do other things in the meantime! We'll play a sound when someone joins.
                </div>
                <div ng-switch-when="matched">
                  You're now chatting with someone from <span ng-class="partner.school">{{partner.school | properSchoolName}}</span>!<br>
                  <div class="question-box">
                    {{message.question}}
                  </div>
                </div>
                <div ng-switch-when="selfRevealed">
                  Your partner's identity will be revealed if they also want to discover yours.
                </div>
                <div ng-switch-when="partnerRevealed">
                  Congratulations! Your partner also wants to know who you are.<br>
                  You've been chatting with: <a href="{{partner.link}}" target="_blank">{{partner.name}}</a> ({{partner.email}})
                </div>
                <div ng-switch-when="fbError">
                  Sorry, there was an error connecting to Facebook. Please try again.
                </div>
                <div ng-switch-when="finished">
                  {{partner.name}} has disconnected. Refresh the page to start another chat!<br>
                </div>
                <div ng-switch-when="reconnecting">
                  Connection lost. Reconnecting...
                </div>
                <div ng-switch-when="reconnected">
                  Reconnected.
                </div>
                <div ng-switch-when="signInError">
                  Please sign in.
                </div>
                <div ng-switch-when="multipleSessionsError">
                  Sorry, you can't chat with more than one person at a time.
                </div>
                <div ng-switch-default>
                  {{message.text}}
                </div>
              </div>
            </div>
          </li>
          <li class="typing" ng-show="partnerTyping && state == 'chatting'">
            {{partner.name}} is typing...
        </ul>
      </div>
      <div class="input-wrapper">
        <textarea
          tabindex="1"
          pom-focus-on-chat
          ng-disabled="state != 'chatting'"
          ng-model="message"
          ng-keydown="sendMessage($event)"
          ng-change="updateTyping()"></textarea>
      </div>
    </div>
    <audio pom-play-on-message src="<%= asset_path('notification.wav') %>"></audio>
    <script src="https://cdn.socket.io/socket.io-1.2.1.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.6/angular.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.6/angular-sanitize.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.6/angular-animate.js"></script>
    <%= javascript_include_tag "chat" %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1 class="hook">There are amazing people you've never met at
  <% School.all.each do |school| %>
    <span class="carousel"><%= school.proper_name %>.</span>
  <% end %>
</h1>
<div class="row how-it-works">
  <div class="col-sm-4">
    <i class="fa fa-users large-icon"></i>
    <h3>1. Join</h3>
    <p>
      We'll pair you with another Ivy League student in an anonymous one-on-one chat and provide a question to get the conversation started.
    </p>
  </div>
  <div class="col-sm-4">
    <i class="fa fa-comments large-icon"></i>
    <h3>2. Chat</h3>
    <p>
      If the conversation goes well, you'll be asked if you want to find out who you're chatting with. Your partner won't know what you choose.
    </p>
  </div>
  <div class="col-sm-4">
    <i class="fa fa-smile-o large-icon"></i>
    <h3>3. Enjoy</h3>
    <p>
      If both people say yes, your identities will be revealed to each other. If not, you'll both stay anonymous. It's completely up to you.
    </p>
  </div>
</div>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 text-center">
    <% if user_signed_in? and current_user.confirmed? %>
      <%= link_to "Start Chatting", chat_path, class: "btn btn-success btn-lg btn-block" %>
    <% elsif user_signed_in? %>
      <button type="button" class="btn btn-success btn-lg btn-block" disabled="disabled">Start Chatting</button>
      <p class="confirm-help">Please confirm your account to start chatting. If you don't see an email from us, try checking your spam folder or
        <%= link_to "resend the confirmation email", user_confirmation_path(user: {email: current_user.email}), method: :post %>.
      </p>
    <% else %>
    <%= bootstrap_form_for(resource, as: resource_name, url: user_registration_path) do |f| %>
        <%= f.email_field :email, hide_label: true, class: "input-lg", autofocus: true, placeholder: "School Email (.edu)" %>
        <%= f.password_field :password, hide_label: true, class: "input-lg", placeholder: "New Password" %>
        <%= f.submit "Sign Up", class: "btn btn-success btn-lg btn-block" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/static_pages/privacy.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2>Privacy Policy</h2>
    <p>
      Your privacy is very important to us. Accordingly, we have developed this Policy in order for you to understand how we collect, use, communicate and disclose and make use of personal information. The following outlines our privacy policy.
    </p>
    <ul>
      <li>
        Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.
      </li>
      <li>
        We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law.
      </li>
      <li>
        We will only retain personal information as long as necessary for the fulfillment of those purposes.
      </li>
      <li>
        We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned.
      </li>
      <li>
        Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.
      </li>
      <li>
        We will protect personal information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.
      </li>
      <li>
        We will make readily available to customers information about our policies and practices relating to the management of personal information.
      </li>
    </ul>
    <p>
      We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained.
    </p>
  </div>
</div>

app/views/static_pages/terms.html.erb
<div class="row">
  <div class="col-sm-12">
    <h2>Web Site Terms and Conditions of Use</h2>
    <h3>1. Terms</h3>
    <p>
      By accessing this web site, you are agreeing to be bound by these
      web site Terms and Conditions of Use, all applicable laws and regulations,
      and agree that you are responsible for compliance with any applicable local
      laws. If you do not agree with any of these terms, you are prohibited from
      using or accessing this site. The materials contained in this web site are
      protected by applicable copyright and trade mark law.
    </p>
    <h3>2. Use License</h3>
    <ol type="a">
      <li>
        Permission is granted to temporarily download one copy of the materials
        (information or software) on Campus Anonymous's web site for personal,
        non-commercial transitory viewing only. This is the grant of a license,
        not a transfer of title, and under this license you may not:
        <ol type="i">
          <li>modify or copy the materials;</li>
          <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
          <li>attempt to decompile or reverse engineer any software contained on Campus Anonymous's web site;</li>
          <li>remove any copyright or other proprietary notations from the materials; or</li>
          <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
        </ol>
      </li>
      <li>
        This license shall automatically terminate if you violate any of these restrictions and may be terminated by Campus Anonymous at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.
      </li>
    </ol>
    <h3>3. Disclaimer</h3>
    <ol type="a">
      <li>
        The materials on Campus Anonymous's web site are provided "as is". Campus Anonymous makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties, including without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Campus Anonymous does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its Internet web site or otherwise relating to such materials or on any sites linked to this site.
      </li>
    </ol>
    <h3>4. Limitations</h3>
    <p>
      In no event shall Campus Anonymous or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption,) arising out of the use or inability to use the materials on Campus Anonymous's Internet site, even if Campus Anonymous or a Campus Anonymous authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.
    </p>
    <h3>5. Revisions and Errata</h3>
    <p>
      The materials appearing on Campus Anonymous's web site could include technical, typographical, or photographic errors. Campus Anonymous does not warrant that any of the materials on its web site are accurate, complete, or current. Campus Anonymous may make changes to the materials contained on its web site at any time without notice. Campus Anonymous does not, however, make any commitment to update the materials.
    </p>
    <h3>6. Links</h3>
    <p>
      Campus Anonymous has not reviewed all of the sites linked to its Internet web site and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Campus Anonymous of the site. Use of any such linked web site is at the user's own risk.
    </p>
    <h3>7. Site Terms of Use Modifications</h3>
    <p>
      Campus Anonymous may revise these terms of use for its web site at any time without notice. By using this web site you are agreeing to be bound by the then current version of these Terms and Conditions of Use.
    </p>
    <h3>8. Governing Law</h3>
    <p>
      Any claim relating to Campus Anonymous's web site shall be governed by the laws of the State of New Jersey without regard to its conflict of law provisions.
    </p>
    <p>
      General Terms and Conditions applicable to Use of a Web Site.
    </p>
  </div>
</div>